# Site settings
title: DR SAMINA KATHAWALA  DDS - CUTE SMILE DENTIST Hackensack NJ  - 52 Summit Ave Hackensack NJ 201 778 0225 2017780225 2017780280 201 778 0280
description: "Dr Samina Kathawala DDS. | Gentle Painless Dentist. Best Dentist serving Hackensack NJ Lodi NJ Saddle Brook NJ Hasbrouck Heights NJ Lodi NJ Elmwood Park NJ Garfield NJ Ridgewood NJ Glen Rock NJ River Edge NJ Teaneck NJ Maywood NJ Paramus NJ Carlstadt NJ East Rutherford NJ South Hackensack NJ Wood Ridge NJ Wood-ridge NJ. 52 Summit Ave Hackensack NJ 07601 201-778-0225"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cutesmilenj.com" # the name of your domain
logo_url: svg/min/logo.svg
permalink: /404.html

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Your Satisfaction is Guaranteed! 
    hero_description: At our practice you will be treated like family.<B> Dr Kathawala </B> and her staff is loving,caring and passionate about your well being. Make an appointment and experience the difference. 

# Contact form
api_token: 79c4fb60ef557a2d31cd16e1300c0d27

# Contact info
contact:

    phone: 201 778 0225
    email: cutesmilesnj@gmail.com
    address: 52 Summit Ave <br> Hackensack NJ <br> 07601
    text: 201 778 0280

# Opening hours
mon_thu: By Appointment Only
friday: 10:00 – 6:30
saturday: 10:00  – 7:00
sunday: 10:00  – 7:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg


# Map
map:
    zoom: 15
    address: 52 Summit Ave, Hackensack NJ
    address_details: svg/min/logo.svg

# Social settings
google: https://www.google.com/search?q=dr+samina+kathawala+DDS
facebook: https://www.facebook.com/pg/Dr-Samina-Kathawala-325513541239783/reviews/?ref=page_internal
healthgrades: https://www.healthgrades.com/dentist/dr-samina-kathawala-g9dkw
#twitter: http://twitter.com
#instagram: http://instagram.com
#youtube: http://youtube.com
#skype: skype:obaez_design?userinfo
# feed: yes

# Footer
copyright: <B> Cute Smiles LLC, <P> 52 Summit Ave, Hackensack NJ 07601 </P> <p>Phone <a style="color:white" href="tel:201 778 0225" > 201 778 0225 </a><B></p> <p>© 2018 CuteSmiles - All rights reserved</p>

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    .gitignore
]

# Theme Settings
bing_site_verification   :
google_site_verification : Hj0p0zna6YPQDuROI9_3uJl0VU1CrXOFTGiF-VLc4XQ
alexa_site_verification  :
yandex_site_verification :

analytics: UA-132426320-1
